// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbwLzP5W9VKwPniw23gs6BAP9bbmJLet4',
    appId: '1:342507582432:web:a49fcc2fe66b4b5a623185',
    messagingSenderId: '342507582432',
    projectId: 'chat-app-d9b86',
    authDomain: 'chat-app-d9b86.firebaseapp.com',
    storageBucket: 'chat-app-d9b86.appspot.com',
    measurementId: 'G-4Z6GY5JBFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEeaUQT2Hgo4bGFijlfohnad58jmqLJCY',
    appId: '1:342507582432:android:eacb4cb534658ea9623185',
    messagingSenderId: '342507582432',
    projectId: 'chat-app-d9b86',
    storageBucket: 'chat-app-d9b86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqJSroFbDgV9_HlBqpxd8ftLDFaCi4q58',
    appId: '1:342507582432:ios:68691ded8696206c623185',
    messagingSenderId: '342507582432',
    projectId: 'chat-app-d9b86',
    storageBucket: 'chat-app-d9b86.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqJSroFbDgV9_HlBqpxd8ftLDFaCi4q58',
    appId: '1:342507582432:ios:90365fa0fca156ef623185',
    messagingSenderId: '342507582432',
    projectId: 'chat-app-d9b86',
    storageBucket: 'chat-app-d9b86.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
